### ISSUE TITLE
Ordering OpenAPI Designer sections in preview window

### ISSUE THREAD

**Issue by Nazarah** [apinf/open-api-designer#100]
# Usability Issue
* OpenAPI Designer follows a specific order of sections (Details, Mime Type,..., etc.)
* However, in preview window, the sections don't appear in that specific order as that in the editor.

# Definition off Done
* [ ] Show sections in preview window by maintaining their order of appearance in the OpenAPI Designer editor.

**Comment by tulir** [comment]
This shouldn't be a problem in the [new UI](https://oai.maunium.net/feature/redesigned-ui) since the preview only shows the data that can be edited in the current form.
