### ISSUE TITLE
Add internationalization support

### ISSUE THREAD

**Issue by brylie** [apinf/open-api-designer#103]
Add internationalization (i18n) support to the project, so that we can translate user interface texts. Once the i18n package is configured, determine how to follow-up with user interface internationalization, including the following
- menu texts
- form texts

**Comment by Nazarah** [comment]
@brylie is issue #99 related to duplicate to this issue? 
If related, I can reference it here.
If duplicate, I can close down the issue.

**Comment by brylie** [comment]
Jep, it is a duplicate. Sorry, I didn't search first.
