### ISSUE TITLE
Deleting the last tag pane action can't be seen unless page is reloaded.

### ISSUE THREAD

**Issue by Nazarah** [apinf/open-api-designer#104]
Reproduction steps:
* Go to http://apinf.org/open-api-designer/tag
* add 5 tags. (no need to fill up fields)
* start deleting the tags from top (stop when the last tag is left).
* click on X button for the last tag pan.

# Result
* removal of tag pane is not immediately visible.
* Page needs to be reloaded to make the action visible.

# System
* windows 8
* Chrome

**Comment by tulir** [comment]
I can't reproduce this at http://apinf.org/open-api-designer/#/tags

@Nazarah Could you check if you can still reproduce this? I merged `master` into `gh-pages` a while ago so it's possible that this bug no longer exists.

**Comment by Nazarah** [comment]
@tulir checked in http://apinf.org/open-api-designer/#/tags
The issue has been fixed.
Closing it.
