### ISSUE TITLE
"Schemes" array is missing

### ISSUE THREAD

**Issue by Nazarah** [apinf/open-api-designer#107]
# Issue
With the latest GUI, "Schemes" array is missing. This should be included within Header section

# Definition of Done:
* [x] Add a new field for Schemes array in Headers section
* [x] 4 checkboxes should be there to support the all 4 possible values under Scheme: (http, https, etc.)

**Comment by brylie** [comment]
@Nazarah could you add a wireframe to this task showing the Schemes array field?

**Comment by Nazarah** [comment]
@brylie I would work on it on Monday.
