### ISSUE TITLE
Add a section to add object definitions

### ISSUE THREAD

**Issue by Nazarah** [apinf/open-api-designer#115]
# User story
>"As an OpenAPI Designer, I should be able create object definitions for my API, so that I can refer them lator in other sections."

In [petstore Swagger](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/petstore.json), an operation response can have a schema where predefined object definitions can be referred.
![image](https://cloud.githubusercontent.com/assets/17976243/26547357/467b9a54-4477-11e7-881a-e8eb2c8d9e70.png)
![image](https://cloud.githubusercontent.com/assets/17976243/26547364/54c9c7d4-4477-11e7-8a93-7e68c5b744eb.png)
This reduces the effort to define Request/Response bodies separately.

# Definition of Done
* [x] A new section "Definitions" should appear in OpenAPI Designer
* [x] A new button should be available to add definitions
* [x] Subfields under a Definition should be available when New button is clicked.

**Comment by tulir** [comment]
There already is a schema editor, called "Types". Only `$ref` support is missing.
