### ISSUE TITLE
Incorporate APINF header and topbar in Open API Designer page

### ISSUE THREAD

**Issue by Nazarah** [apinf/open-api-designer#14]
![image](https://cloud.githubusercontent.com/assets/17976243/20394800/721d6758-ace9-11e6-8e57-c5c04aa361e0.png)

open question: should we link this page with regular APINF platform? (a new menu in the Topbar)
Or should we have this option as an "Add" funtionality (e.g. similar to Add API)

**Comment by bajiat** [comment]
Not needed at this point. This is a separate project and we can integrate it to Apinf e.g. if it will be a package later.
