### ISSUE TITLE
Add button to clear cached Swagger document

### ISSUE THREAD

**Issue by tulir** [apinf/open-api-designer#157]
Currently the only quick way to clear the data is to go to the console and use `delete localStorage.cachedForm`.
We need an easier way to clear the data, but we need to make sure that it isn't easy to clear the data accidentally.

**Comment by Nazarah** [comment]
If there is a button in UI for clear the form data, make sure you add a confirmation dialogue to warn user about the action. After he confirms, perhaps show an s-alert to indicate the forms have been cleared.

Some text for the confirmation  dialogue is:
"You are about the clear all form data. This action can't be undone. Are you sure to proceed? Yes, No"

S-alert text about confirming the action:
Form data have been cleared.
