### ISSUE TITLE
Repeating sections in Paths -> Methods 

### ISSUE THREAD

**Issue by Nazarah** [apinf/open-api-designer#16]
Right now when a method is added under a path, Schemes, Consumes, Produces and Parameters sections appear along with the new fields (Method Types, Tags, Summary, Description, External Documentation: URL, Description, Operation ID, etc.).
It seems the Schemes, Consumes, Produces and Parameters sections are added repeatedly.
Is it done intentionally or is this a bug?
![pathmethodparameters](https://cloud.githubusercontent.com/assets/17976243/20426091/2a6a9a46-ad86-11e6-8003-b57c86794ba2.gif)

**Comment by tulir** [comment]
The OpenAPI spec allows you to define the four fields separately for each path method, but they're not required. The higher-level fields are used when a path method doesn't have it's own definitions.

**Comment by Nazarah** [comment]
Would it be possible to provide this information somewhere in the UI?
There is an issue for adding tooltip for each fields.
Perhaps this information can be added for Path Method section.

**Comment by kyyberi** [comment]
I like the effort. However I fear that the UI will be a challenge. Making it usable is a challenge. Might make sense to try approach which was applied in adding API to catalogue.

**Comment by bajiat** [comment]
@kyyberi Nazarah is looking into breaking the UI into sections. It would be a good idea to discuss with developers, like you suggested.

**Comment by xylix** [comment]
This should have been closed ages ago. UI has been split into sections for around 6 months now.
