### ISSUE TITLE
Icons not rendering in demo site

### ISSUE THREAD

**Issue by brylie** [apinf/open-api-designer#2]
On the demo site, the icons next to required fields and validation messages are not rendering:

![screenshot_20161107_164501](https://cloud.githubusercontent.com/assets/17307/20061698/9cf36640-a509-11e6-9cc5-0fb07a3e39f0.png)

**Comment by brylie** [comment]
Ping @Xylix @tulir

**Comment by philippeluickx** [comment]
I am having similar issues with some icons in the controls.

![image](https://cloud.githubusercontent.com/assets/836866/20092197/75e96676-a59f-11e6-839d-d5a196c32c84.png)


Getting this in console:

Failed to load resource: the server responded with a status of 404 (Not Found)
http://apinf.org/open-api-designer/node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.woff Failed to load resource: the server responded with a status of 404 (Not Found)
http://apinf.org/open-api-designer/node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by brylie** [comment]
I also see the following console errors:

```js
downloadable font: download failed (font-family: "Glyphicons Halflings" style:normal weight:normal stretch:normal src index:1): status=2147746065 source: http://apinf.org/open-api-designer/node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2open-api-designer:278:12
downloadable font: download failed (font-family: "Glyphicons Halflings" style:normal weight:normal stretch:normal src index:2): status=2147746065 source: http://apinf.org/open-api-designer/node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.woffopen-api-designer:278:12
downloadable font: download failed (font-family: "Glyphicons Halflings" style:normal weight:normal stretch:normal src index:3): status=2147746065 source: http://apinf.org/open-api-designer/node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
```

**Comment by tulir** [comment]
The files are there in the `gh-pages` branch, and I haven't been able to reproduce this locally. Does Github Pages do something funny with non-text and/or font files?

**Comment by philippeluickx** [comment]
Maybe relative imports or getting messed up?

**Comment by brylie** [comment]
Ah, that makes sense. It may not like distributing the web font `.ttf` binaries. Can we solve this with a CDN?

**Comment by brylie** [comment]
That, or it might be worth putting the `.ttf` files in an `/assets` folder:

- https://gist.github.com/mattnorris/5307093#directory-structure

**Comment by brylie** [comment]
Regardless, this is not super-urgent. So, we can come back to the issue later.

**Comment by brylie** [comment]
This might also be relevant:

- [Bootstrap Glyphicons with Webpack](https://github.com/webpack/webpack/issues/597)

**Comment by philippeluickx** [comment]
Seems like you can actually just use the whole bootstrap for CDN. Might be a good idea considering it's widely used and probably already cached on the users machine?
`<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" type="text/css" rel="stylesheet">`
