### ISSUE TITLE
Make sure the Swagger file validates

### ISSUE THREAD

**Issue by bajiat** [apinf/open-api-designer#21]
Ensure that the json that is parsed from the user input passes Swagger validation. You can use for example this validator to check: http://bigstickcarpet.com/swagger-parser/www/index.html

Paste the output you are producing and see if it validates. Take necessary action to make it pass. For example, the json probably needs to start with Swagger version even if it was not part of the form UI.

**Comment by tulir** [comment]
I think I forgot to re-add the Swagger version to the output when removing it from the UI.
In addition to that, empty fields should probably be removed when processing the output JSON and the `host` and `basePath` fields (currently in `info`) need to be moved to the correct place.

**Comment by tulir** [comment]
Commit cd7da3f fixes some validation problems

**Comment by tulir** [comment]
Superseded by #121
