### ISSUE TITLE
Replace the item button with more meaningful button

### ISSUE THREAD

**Issue by bajiat** [apinf/open-api-designer#23]
Please use a more meaningful label for the item button. You are using the item button for instance in Paths section, while for instance in MIME type the label is the item = MIME type you are adding or deleting.

Compare the following:
<img width="613" alt="swagger editor button" src="https://cloud.githubusercontent.com/assets/11626388/20836597/c508b22c-b8a8-11e6-9d58-65c42bff45e5.png">

<img width="484" alt="swagger editor mime type" src="https://cloud.githubusercontent.com/assets/11626388/20836604/c941bac8-b8a8-11e6-80dc-492953aa08b0.png">

**Comment by bajiat** [comment]
@Nazarah You could also take a look. See if there is something you can suggest what comes to adding items.

**Comment by tulir** [comment]
This should be pretty easy to fix. The `items` section in the relevant part of the schema just needs its own `title` attribute.

**Comment by xylix** [comment]
Fixed in commit a2f300b
