### ISSUE TITLE
Add button to reset form

### ISSUE THREAD

**Issue by brylie** [apinf/open-api-designer#25]
It is difficult to reset the designer interface. Even a 'clear all cache' refresh leaves the form populated with previous values.

# Feature request
Add some way for users to manually reset the form values.

**Comment by tulir** [comment]
The cache is stored in the localStorage, so we can just add a button that executes
```javascript
delete localStorage.cachedForm
```

**Comment by xylix** [comment]
Added button in commit 732df17
