### ISSUE TITLE
Consider branding the designer with APInf elements

### ISSUE THREAD

**Issue by bajiat** [apinf/open-api-designer#33]
These elements could be logo, title, colors

@Nazarah Let's look at the UI and discuss the options for branding the designer

**Comment by Nazarah** [comment]
@bajiat does this require a front page with information about the purpose for the open API Designer?
And then perhaps a get started button to navigate to the actual page that has the editor?
A few other option would be to mention about the developers working on it and a contact form?

**Comment by Nazarah** [comment]
@tulir @xylix : Is it possible to look at the latest version? As I would be working on branding this page, this would be good to look at the latest version first and then make the sketches.

**Comment by xylix** [comment]
Deprecated by #39
