### ISSUE TITLE
Consider changing from MIT to AGPL license

### ISSUE THREAD

**Issue by bajiat** [apinf/open-api-designer#34]
https://tldrlegal.com/license/mit-license
https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0)

**Comment by kyyberi** [comment]
For what I have heard, business is rather allergic to AGPL. It is rather limiting, hard to be compliant with.

**Comment by xylix** [comment]
Project is going to use the MIT licence for now.
