### ISSUE TITLE
On loading the page for the 1st time, user doesn't know at which part of the documentation is in front view

### ISSUE THREAD

**Issue by Nazarah** [apinf/open-api-designer#38]
![image](https://cloud.githubusercontent.com/assets/17976243/22931712/5f051da2-f2ce-11e6-9906-877df1593bc5.png)

When the page is loaded for the 1st time, the Info section should be selected/highlighted.
But it doesn't happen.
When user browse other sections and then clicks on Info section, it then appears as selected.

**Comment by xylix** [comment]
The aurelia version will need a new issue for this problem once it becomes relevant (aurelia version does not yet have a navigation bar)
