### ISSUE TITLE
Branding of Open API Page

### ISSUE THREAD

**Issue by Nazarah** [apinf/open-api-designer#39]
Low fidelity prototype describing how the current view can be migrated to standard APINF branding

# Wirefames

1. Homepage:
![brandingalt](https://cloud.githubusercontent.com/assets/17976243/22966011/01ce9a78-f369-11e6-9200-7e7f78616dfb.png)

2. About page
![brandingabout](https://cloud.githubusercontent.com/assets/17976243/22966029/14bd63f8-f369-11e6-9038-f5ade6f13fdf.png)

3. Contributor page
![brandingcontributers](https://cloud.githubusercontent.com/assets/17976243/22966049/25afcb6a-f369-11e6-8b2e-fdb9be82c080.png)

keeping the option of chatbot instead of contact form.
Whenever user comes to open-api-designer, chatbot would open up and request the user to provide their name and email address so that someone from APINF can get back to them

**Comment by bajiat** [comment]
Some comments
* 'APINF' in the footer should be 'APInf'
* What if the About was not an entire page, but just a modal (partial view) with information like version, contributors, link to repository. Compare with current About view in APInf UI.
* 'Home' could be 'Editor'?

**Comment by Nazarah** [comment]
I have made the changes as u suggested.
however, as it was also about branding, I thought it would have been cool to see a separate About section with descriptions about Open API Design (why it is needed, or whom it is intended to, etc.). We also can also include the important links in that page.
Plus the style of contributors was similar the style of our apinf.org page.
But if we lack time, by all means, we can go with the quick solutions.

![brandingalt](https://cloud.githubusercontent.com/assets/17976243/23021371/47b6c718-f454-11e6-8b80-705ba3c2db9b.png)

![banding2](https://cloud.githubusercontent.com/assets/17976243/23021384/5245e07e-f454-11e6-9d98-4ad0f95979ff.png)
