### ISSUE TITLE
Redesigning UI for editor and preview window

### ISSUE THREAD

**Issue by Nazarah** [apinf/open-api-designer#40]
- [ ] looking for BS elements that can be used to replace current UI of editor and json preview window

- [ ] designing low fidelity prototypes for the UI

**Comment by bajiat** [comment]
@Nazarah It would be useful if you could talk to @tulir and @xylix about the current demo and wireframes

**Comment by Nazarah** [comment]
@bajiat we'll have a meeting on 22 May, 2017 14:00.
We'll discuss about possible improvements in the UI based on the laetst demo.

**Comment by MikeRalphson** [comment]
One thing I have noticed about your project is your visual design previously followed the structure of the OpenAPI specification very closely. I feel that has benefits for people familiar with or learning about the specification but it might also limit your UX choices, i.e. the UI does not necessarily need to expose all of the aspects of the specification (such as parameters being held at three levels - this could be handled by automatic placement of parameters when they are created/copied/modified, or by a post-processing step before the API definition is saved).

Happy to look at any wireframes etc. Areas where OpenAPI-GUI currently deviates from exposing the OpenAPI specification structure are:

* hiding the details of shared, path-level and operation-level parameters
* hiding the details of shared models/definitions (incomplete)
* using an 'apply to all paths' checkbox for securityDefinitions (incomplete)
* folding `externalDocs` properties into the `tag` object
* similar flattening of the `info` object sub-objects (as there can be only one of each)
* use of checkboxes for protocol schemes, not a list

**Comment by Nazarah** [comment]
Hi @MikeRalphson welcome onboard. :)

A few questions to you:
1.
> the UI does not necessarily need to expose all of the aspects of the specification (such as parameters being held at three levels - this could be handled by automatic placement of parameters when they are created/copied/modified

Do you mean showing the details of Path element in the preview window or the editor itself?
2. 
> folding externalDocs properties into the tag object

In current UI, external doc is a separate textfield in header section. 
Are you suggesting to define this as a Tag?

3.
> hiding the details of shared, path-level and operation-level parameters

![image](https://cloud.githubusercontent.com/assets/17976243/26404548/077a79ea-409b-11e7-8dfa-eca8193d7926.png)
this is a reference from http://openapi-gui.herokuapp.com/
Here they have specified parameters of path elements as tabs.
This somehow make it easier to browse through them, specially if there is more than on path is defined.
Do you have some different opinion about this design?
If so, can you give us an example about how the UI (editor or preview) can be?

**Comment by Nazarah** [comment]
@tulir @xylix @JeHugawa here is an initial sketch about how I see the UI
![openapidesigner](https://cloud.githubusercontent.com/assets/17976243/26405167/29721632-409d-11e7-80e2-af1698f4170d.png)
* view includes a topbar showing OpenAPI Designer Logo and links to know about version information and navigation to GitHub repo
* footer includes Powered by: APInf footer text (or logo, can be hardcoded)
* sections now appear as tabs (something similar to  [here](http://openapi-gui.herokuapp.com/) minus the tab logo.
* About section appears as a tab as well where there is information about what is OpenAPI Designer and how it can be used. (can be hardcoded for the time being if it seems feasible)
![openapidesigner2](https://cloud.githubusercontent.com/assets/17976243/26405669/af379494-409e-11e7-9f07-c70b799eb73c.png)

* each section has its own preview window so that there is no excess information and giving chance the user to focus more on the current content. 

can u guys give me your feedback about it.
This is only about the page layout and branding.
I still need to work with specific sections.

**Comment by xylix** [comment]
The wireframe's layout and branding looks fine to me. We need the pictures (logo's and icons) to implement it into the editor.

The space between the top Open API Designer branding at the top and the About, Header etc. top bar could be smaller vertically.

**Comment by tulir** [comment]
There's an initial implementation of the wireframe in the `feature/redesigned-ui` branch (hosted version available at https://oai.maunium.net/feature/redesigned-ui/). There are no images, but the placeholder can be easily replaced with real images.

**Comment by Nazarah** [comment]
@xylix for icons, please use [font awesome ](http://fontawesome.io/). 
We need icons for GitHub navigation, Info icon, Download, Save and Reload icons.
I would be able to deliver the logo on Monday. I need to make a low fi sketch and get approval for it.

**Comment by Nazarah** [comment]
**Update about logo:** We will go with the current logo of APInf, with text for the platform "OpenAPI Designer". 
In the footer, we'll simply write Power by APInf.
I'll put the logo in this issue by the end of the day

**Comment by Nazarah** [comment]
@tulir @JeHugawa @xylix logos are attached as PNG image
1. Black text
![logo1](https://cloud.githubusercontent.com/assets/17976243/26542320/1e075a14-4462-11e7-90ed-25dd96d0ced4.png)

2. White text
![logo2](https://cloud.githubusercontent.com/assets/17976243/26542331/2c53370a-4462-11e7-9611-0f53f20943b4.png)

3. (In case only using the circles and adding sitename as html code)
![logo3](https://cloud.githubusercontent.com/assets/17976243/26542352/3db9fcfe-4462-11e7-8e17-f7317a577bd3.png)
Use the font "Montserrat" for writing the logo text.

**Comment by Nazarah** [comment]
@tulir had a look in the GUI that was provided in [this link](https://oai.maunium.net/feature/redesigned-ui/).
There are some feedback
1. Please use tab styling from [bootstrap](http://getbootstrap.com/components/#nav-tabs). 
The current style of tab is not favorable to us.
2. Add some margins in the container. Right now all the page content is almost touching the container boundary.
3. keep some space between the topbar and tabs.

**Comment by tulir** [comment]
@Nazarah 
I've copied the Bootstrap tab styling, removed the outermost border from the main form, added some padding for the main view (form + preview) and added more margin after the topbar.

The top logo and info/github icons have been added. I wasn't quite sure how the download buttons should be implemented, so I temporarily added the format after the icon. I'm guessing a dropdown would be best. Any thoughts?

About the footer: should we just write "Powered by APInf"? If so, does the font matter and how large should the text be?

The latest changes are again available in [feature/redesigned-ui](https://oai.maunium.net/feature/redesigned-ui/)

**Comment by Nazarah** [comment]
@tulir 
1. Please go with the dropdown for download option.
(**additional question**: is the document going to be auto saved in every 5 seconds? If not, I suggest adding a Save button. Also in that case, if user wants to close the browser tab/window or want to go back to a previous page, a POPUP can appear saying "Changes will not be saved. Proceed? Yes.No")

2. I am adding the APInf logo, which you can add in the footer.
BlackLogo
![apinf_logo_black_1](https://cloud.githubusercontent.com/assets/17976243/26569803/8ec8a2d6-4515-11e7-8d93-3a1ed8b5618d.png)

White Logo
![apinf_logo](https://cloud.githubusercontent.com/assets/17976243/26569813/9f53a07e-4515-11e7-80bc-af70db38ca06.png)

3. would you consider adding some margins in the container?

**Comment by tulir** [comment]
Changes are (supposed to be) saved to `localStorage` instantly. It doesn't do that in the current state of the `redesigned-ui` branch though. I'll fix that before the merge.
Uploading changes to the server won't be automatic, so once we have a persistence layer, we should probably add an upload/save button.

**Comment by Nazarah** [comment]
@tulir no need to work on immediately but would you consider keeping the topbar and section tabs sticky? this is because when we are adding paths and operation, there can be many. And having a quick access to the document section is user friendly and lets user know their current location in OpenAPI Designer.

**Comment by tulir** [comment]
I've made the navigation bar sticky for non-crappy browsers (pretty much everything except IE/Edge, see https://caniuse.com/#feat=css-sticky). I don't think the brand topbar should be sticky since it doesn't contain anything that's needed much.

**Comment by Nazarah** [comment]
@tulir where can I see the latest developed UI?

**Comment by tulir** [comment]
@Nazarah https://oai.maunium.net/feature/redesigned-ui should now have the latest changes
