### ISSUE TITLE
Make API Documentation Section Pane floating

### ISSUE THREAD

**Issue by Nazarah** [apinf/open-api-designer#42]
#  Issue
Some sections of the Open API Designer is longer. So on scrolling down, the Section Pane gets hidden on top. It would be prudent so make the section pane floatable. This would allow the user to be aware of where s/he is currently in the documentation editor.

**Comment by Nazarah** [comment]
One more implementation idea can be to show the sections as nav menu and making it sticky.
@tulir and others, what are your opinion about this?

**Comment by xylix** [comment]
Closed because the nav menu in the new user interface is now sticky.
