### ISSUE TITLE
Info text for Host field should be more intuitive

### ISSUE THREAD

**Issue by Nazarah** [apinf/open-api-designer#47]
# Issue
The info message given for Host field is vauge. It doesn't clearly state the purpose of the field, how is it related to Base field and what example value should be given in it.

# Solution
Give intuitive text explaining the above description for Host field.

**Comment by Nazarah** [comment]
Update: would be tested when INFO tip for fields get implemented.
Related issue: #105

**Comment by tulir** [comment]
Closing in favor of #170
