### ISSUE TITLE
After a while preview window stops showing added field values

### ISSUE THREAD

**Issue by Nazarah** [apinf/open-api-designer#48]
![image](https://cloud.githubusercontent.com/assets/17976243/23985264/beb490a6-0a26-11e7-8516-febde60efde6.png)

Under "Paths" section, user was giving values for Response subsection.
None of the values added appeared in the preview window under Response.
Afterwards in subsequent sections, no values added in the editor appeared in the preview window.

**Comment by xylix** [comment]
Not relevant to the new version of the editor, but we will check for this problem after "Paths" section is implemented in the aurelia version.
