### ISSUE TITLE
On clicking "Add New Item" button under Paths section, the entire GUI gets disappeared.

### ISSUE THREAD

**Issue by Nazarah** [apinf/open-api-designer#5]
![swagerpagebug](https://cloud.githubusercontent.com/assets/17976243/20097732/a5663f14-a5b8-11e6-98e0-f87f62f159ce.gif)

* OS: Windows 8
* Browser: Chrome, FF

**Comment by tulir** [comment]
The paths object probably has a small mistake somewhere. Shouldn't be hard to find and fix.
