### ISSUE TITLE
Path field doesn't maintain Regular expression checking. It accepts any sequence of characters

### ISSUE THREAD

**Issue by Nazarah** [apinf/open-api-designer#51]
![image](https://cloud.githubusercontent.com/assets/17976243/23985516/37f61682-0a28-11e7-8682-07f98b904226.png)

**Comment by Nazarah** [comment]
**Update**: This would be tested once Path element is implemented.
@tulir @xylix keep this issue in your mind when implementing the path element.

**Comment by xylix** [comment]
Closing in favor of #171.
