### ISSUE TITLE
Path GUI Bug

### ISSUE THREAD

**Issue by Nazarah** [apinf/open-api-designer#52]
![image](https://cloud.githubusercontent.com/assets/17976243/23985932/459be440-0a2a-11e7-8f57-7e164cdc7499.png)

1. On adding a new Path, the GUI of panes overlap with each other
2. On Adding Path attribute value, it comes out of the blue pane
( above cases also happens with Security Definitions section)

**Comment by Nazarah** [comment]
@tulir  @xylix please investigate this issue when you are implementing the Path element for the new UI.

**Comment by xylix** [comment]
Not a problem in the new implementation.
