### ISSUE TITLE
Consumes & Produces sections: Add info tip explaining what is MIME type, why it is needed and possible value example

### ISSUE THREAD

**Issue by Nazarah** [apinf/open-api-designer#53]
# Issue
In usability testing, participant had to google to know what is MIME and what can be its possible value.
It is not clear in the view why MIME type is needed.

# Solution
1. Add info tips in Consumes and Produces sections giving information about what are these and why they are needed.
2.There should be info tip stating the above information in Consumes and Produces Section

**Comment by Nazarah** [comment]
**Update**: Issue would be tested when INFO tip has been implemented and added to the new UI.

**Comment by tulir** [comment]
Closing in favor of #170
