### ISSUE TITLE
Swapping function of values should be made more intuitive

### ISSUE THREAD

**Issue by Nazarah** [apinf/open-api-designer#55]
Currently (in Consumes and Produces sections) if multiple values are swapped within each other, the action is not always clearly visible and intuitive. It takes user a while to understand that the values have been swapped to other fields. Some kind of feedback (hourglass, s-alert, etc.) would be good to indicate this action.

**Comment by xylix** [comment]
Not relevant after UI redesign and implementation. There is no longer swapping functionality.
