### ISSUE TITLE
GUI becomes difficult to track when more elements are added into the documentation

### ISSUE THREAD

**Issue by Nazarah** [apinf/open-api-designer#57]
# Issue
Especially in path section, when more subsections are added and each subsection has more than one elements, it becomes difficult to track which element is under which sub-section or parent field.
![openapipath](https://cloud.githubusercontent.com/assets/17976243/23987173/ee06f3d0-0a30-11e7-9541-52b88b7fe8b7.gif)

**Comment by Nazarah** [comment]
**Update**: this needs to be checked when the Path section has been implemented in the latest UI

**Comment by xylix** [comment]
New UI fixes this problem.
