### ISSUE TITLE
Headers, Examples, Tags, Consumes and produces subsections under Path section should have info text explaining their purpose

### ISSUE THREAD

**Issue by Nazarah** [apinf/open-api-designer#59]
![image](https://cloud.githubusercontent.com/assets/17976243/23987630/31b71798-0a33-11e7-9048-2e8193797bf2.png)

**Comment by Nazarah** [comment]
Related issues: #53 #105

**Comment by Nazarah** [comment]
**Update:** The issue would be tested when Path element is implemented and related issues are updated/implemented.

**Comment by tulir** [comment]
Closing in favor of #170
