### ISSUE TITLE
Info icons and help texts for fields

### ISSUE THREAD

**Issue by bajiat** [apinf/open-api-designer#6]
Place an icon to the same row as the tile. The icon could e.g. be a circle with letter 'i'. 
When user clicks over the icon, a help text explaining the purpose of the field appears.

<img width="259" alt="info icon" src="https://cloud.githubusercontent.com/assets/11626388/20100158/e0fd14c4-a5c4-11e6-81f1-ec75344f43fb.png">

**Comment by Nazarah** [comment]
If possible, include what part of the json file would be affected by the value given in each field.

**Comment by tulir** [comment]
Support for info icons added in e998081 using schema `description` field

**Comment by xylix** [comment]
Some descriptions added in commit ceaaa6d

**Comment by tulir** [comment]
We need to figure out which fields need the info button.

Info buttons can be added using the `infoText` property inside the schema `options`. We decided to move it to `options.infoText`, since the `description` field was already used for a different style of descriptions.

Example usage:
```
{
  "type": "string",
  "options": {
    "infoText": "This field wants a string."
  }
}
```
