### ISSUE TITLE
Frontend/backend framework choice

### ISSUE THREAD

**Issue by tulir** [apinf/open-api-designer#64]
We'll probably want to use Meteor for the persistence layer (#36), so we need to decide if we want to switch to Meteor completely or use an Aurelia frontend with a Meteor backend.

Here are some pros and cons for both options

Aurelia frontend with Meteor backend
* Pros
  * We have a good form system built
* Cons
  * It may be harder to integrate Aurelia with Meteor

Full-stack Meteor
* Pros
  * Other APInf projects use Meteor
  * It's more common so there are more libraries available which could reduce the amount of code needed
* Cons
  * We'll have to rewrite most of the code

# Goal
* [x] Choose a frontend framework
  - Got approval to continue working with [Aurelia](http://aurelia.io/)
* [x] Choose a backend/REST framework

**Comment by brylie** [comment]
Good points. We should make a decision soon, to continue the project. What is your preference?

**Comment by brylie** [comment]
We had a leadership meeting this morning, and it was decided that we can use this project as an innovation experiment. Basically, I am hoping that Aurelia will introduce us to new best practices for front-end architecture. So, we are free to move forward, and possibly fail, with Aurelia.

**Comment by brylie** [comment]
It is also worth mentioning that we can treat this project as a stand-alone tool, kind of like a microservice. There is a general need in the OpenAPI community for an open source visual design tool, so we have a chance to meet that need.

**Comment by brylie** [comment]
cc: @bajiat @ccsr

**Comment by tulir** [comment]
So should we use Meteor or something else for the backend? I'm more familiar with Go and Python, but we can also use Node.js.

**Comment by brylie** [comment]
If possible, I would like for us to use a single language (JavaScript) for front/backend. What Node.js MVC framework(s) might we compare?

For a specific suggestion, I recommend the [Sails.js](http://sailsjs.com/) framework, and have worked with it a bit.

**Comment by mauriciovieira** [comment]
For the sake of innovation experiment, my suggestion is [Mean](https://github.com/meanjs/mean), it gives a good scaffold on front-end as well as back-end testing.

**Comment by brylie** [comment]
Cool, lets add consider Mean and Sails.js for a comparison. Any other suggestions?

FWIW, GitHub has a [list of web application frameworks](https://github.com/showcases/web-application-frameworks).

**Comment by brylie** [comment]
Using the GitHub web aplication frameworks list, we can compare Sails.js and MEAN directly (to a certain extent).

![screenshot_20170324_101450](https://cloud.githubusercontent.com/assets/17307/24285857/d15b01e0-107a-11e7-8327-3c23834feb93.png)

Observations:
- MEAN has more forks/branches
  - MEAN: 2,954
  - Sails.js: 1,691
- Sails.js has more stargazers
  - Sails.js: 16,739
  - MEAN: 9,900
- Sails.js seems to have more recent activity (although the scales are ambiguous)

**Comment by brylie** [comment]
Here is a closer look at the development activity for MEAN and Sails.js. The highlighted area starts at 2016-01-01 and extends to 2017-03-24.

![screenshot_20170324_102231](https://cloud.githubusercontent.com/assets/17307/24286032/d0676a7a-107b-11e7-992a-13474f17ffd2.png)

![screenshot_20170324_102329](https://cloud.githubusercontent.com/assets/17307/24286048/eeca635a-107b-11e7-8cef-b0312d8dedd7.png)

**Comment by brylie** [comment]
As an aside, would are some thoughts on using Django for the backend?

**Comment by tulir** [comment]
I prefer Flask since it's light and easy to use. Django is also fine, but I haven't used it that much.

**Comment by brylie** [comment]
Cool. Flask sounds good. Let me check with @bajiat.

**Comment by brylie** [comment]
@ccsr agreed that Flask sounds good, particularly since we want to keep the backend as simple as possible.

**Comment by brylie** [comment]
Next decision, what database do you want to use with Flask?

**Comment by brylie** [comment]
After a quick search, I think we should stick close to the recipe shown in [Web API Development with Flask ](http://shop.oreilly.com/product/0636920050339.do). That means:

- Flask (of course)
- SQAlchemy (orm)
- MySQL, MariaDB, or Postgres

**Comment by bajiat** [comment]
What would this mean in practise for integration with APInf?

**Comment by brylie** [comment]
It means that APInf would retrieve the OpenAPI document via an HTTP endpoint. We will have to figure out a simple way for the API Owner to get the HTTP endpoint from the OpenAPI Designer, and add it to the API Documentation settings.

**Comment by xylix** [comment]
The backend will use Flask with SQAlchemy
