### ISSUE TITLE
Benchmark RAML designers and other API design tools

### ISSUE THREAD

**Issue by bajiat** [apinf/open-api-designer#66]
_From @kyyberi on November 3, 2015 16:59_

RAML spec versio 1.0 is out and in the same time tools have been put out. 

"API Designer is a standalone/embeddable editor for RAML (RESTful API Modeling Language) written in JavaScript using Angular.JS. By default, the editor uses an in-browser filesystem stored in HTML5 Localstorage."

https://github.com/mulesoft/api-designer

_Copied from original issue: apinf/platform#576_

# Goal
Benchmark 1-2 other API designer tools
List the benefits and pros and cons
Create enhancement issues based on existing wireframes

**Comment by xylix** [comment]
Succeeded by #119
