### ISSUE TITLE
Cleanup issues

### ISSUE THREAD

**Issue by xylix** [apinf/open-api-designer#68]
There are many issues leftover from the pre-aurelia version of open-api-designer. These need to be cleaned.

**Comment by xylix** [comment]
We need to think how relevant the usage issues from the previous versions are to the current and future versions of the editor.

**Comment by xylix** [comment]
@Nazarah is going to check some of the usage issues made for the older, json-editor based editor, and determine which are still relevant.

**Comment by tulir** [comment]
We should probably close the old info text issues since they're not complete and quite hard to see what is needed. As a replacement, one central issue for info texts would probably be good.

**Comment by xylix** [comment]
Issues have now been cleaned up.
