### ISSUE TITLE
Divide design form into sections

### ISSUE THREAD

**Issue by brylie** [apinf/open-api-designer#7]
The design form is currently very long, and expected to grow. Design/research some possible solutions for making the form shorter, e.g. a multi-step wizard or collapsible sections. Make changes to the form structure based on the design decision and possibilities for the autogenerated form.

**Comment by tulir** [comment]
b406c9620ed8c6702eedae1958f511c08022be6f (in branch ui1) splits up the different major sections of the schema and splits them into separate views.

**Comment by tulir** [comment]
ui1 was merged into master, so this issue is resolved.
