### ISSUE TITLE
Create a simple persistence layer

### ISSUE THREAD

**Issue by xylix** [apinf/open-api-designer#70]
The backend will use the python framework Flask with SQLAlchemy to implement exporting and importing documents to and from a server.

**Comment by mauriciovieira** [comment]
Shouldn't this backend part be a separated repository?

**Comment by brylie** [comment]
> Shouldn't this backend part be a separated repository?

We discussed that briefly, and decided that it is simpler for now to keep the projects together. @mauriciovieira , if you have a strong recommendation here, we can go with your direction.

**Comment by brylie** [comment]
On second thought, and given that we are discussing collaborating with OpenAPI GUI project, a stand-alone repository for the persistence layer might make things easier. @xylix, @JeHugawa, @MikeRalphson, @mauriciovieira thoughts?

**Comment by MikeRalphson** [comment]
Will the persistence layer be hosted with an open API or for local deployments only? I'm planning at some stage to add pluggable storage backends, i.e. the existing [localStorage](https://github.com/Mermade/openapi-gui/blob/buefy/docs/technical.md#storage-engines) one, and  integration with the [SwaggerHub API](http://swagger.io/integrating-with-the-swaggerhub-api/). We could collaborate on a compatible DB schema and/or a standard for localStorage and IndexedDB usage, default ports etc?

**Comment by brylie** [comment]
> Will the persistence layer be hosted with an open API or for local deployments only?

It seems reasonable that we could host this persistence layer and offer an open API. We will need to take into consideration authentication/access control. What are your thoughts?

**Comment by MikeRalphson** [comment]
> We will need to take into consideration authentication/access control. What are your thoughts?

I have asked the question as to what license applies to the SwaggerHub API design as I think it is mostly very clean and capable. Some kind of authentication integration with GitHub might also be worth looking at (as apinf.io already has it). A generated API key on the apinf.io account page would probably be simplest. 

BTW you may not know that I'm also the current maintainer of the [APIs.guru API directory](https://apis.guru/browse-apis/) so perhaps there are also other opportunities to collaborate.

**Comment by mauriciovieira** [comment]
> if you have a strong recommendation here, we can go with your direction.

I don't have a strong recommendation. We can either choose for a full stack project or a front-end + back-end project. Even before reading @MikeRalphson's invitations for collaboration, I thought that we'd profit more with a separate backend.

> On second thought, and given that we are discussing collaborating with OpenAPI GUI project, a stand-alone repository for the persistence layer might make things easier.

So I'd go with a separate project for backend. This is my vote 👍 

>  We could collaborate on a compatible DB schema and/or a standard for localStorage and IndexedDB usage, default ports etc?

Yes! If we agree on that, we reopen https://github.com/apinf/open-api-designer/issues/36 for discussion and stop work at #82 by now.

**Comment by JeHugawa** [comment]
I will continue working on  #82 for now, thought  i hope that we can make a decision as soon as possible. I have no much preference in this matter.

**Comment by MikeRalphson** [comment]
> It seems reasonable that we could host this persistence layer and offer an open API.

I have had it [confirmed](https://twitter.com/fehguy/status/866703990414688257) by @fehguy (thanks Tony) that the [SwaggerHub API design](https://api.swaggerhub.com/apis/swagger-hub/registry-api/1.0.41) is licensed under the [Creative Commons 4.0 International](https://creativecommons.org/licenses/by/4.0/) license (though it may be the [ShareAlike](https://creativecommons.org/licenses/by-sa/4.0/) variant). I think it's an excellent starting point for an API collaboration API, to save re-inventing the wheel, with the added benefit of SwaggerHub compatibility.

* [API documentation](http://swagger.io/integrating-with-the-swaggerhub-api/)
* [Swagger-UI](http://petstore.swagger.io/?url=https://api.swaggerhub.com/apis/swagger-hub/registry-api/1.0.41)

**Comment by MikeRalphson** [comment]
It may be worth considering using [connexion](https://github.com/zalando/connexion) which is a Swagger/OpenAPI-led design-first framework on top of Flask.

I was able to import the SwaggerHub API definition and [create a stubbed server](https://github.com/Mermade/apipl) very quickly.

**Comment by brylie** [comment]
@MikeRalphson, @mauriciovieira, @tulir, @xylix, @JeHugawa: Where should we collaborate on this backend project?

**Comment by MikeRalphson** [comment]
Happy for it to be an apinf org repository.

**Comment by tulir** [comment]
@brylie @MikeRalphson @mauriciovieira @xylix @JeHugawa I've created a new repository: [apinf/open-api-hub](https://github.com/apinf/open-api-hub). I also made a new issue for discussion about the backend: apinf/open-api-hub#1

**Comment by brylie** [comment]
Renamed repository to 'openapi-hub'

https://github.com/apinf/openapi-hub/

**Comment by xylix** [comment]
Closing in favor of apinf/openapi-hub#1

**Comment by tulir** [comment]
The persistence layer branch has been removed, but the data is still available at http://oai.maunium.net/persistence-layer.zip
