### ISSUE TITLE
UX review for 1.0 release

### ISSUE THREAD

**Issue by brylie** [apinf/open-api-designer#73]
Once there is a working demo, review the user interface and functionality from a user experience perspective. Provide any feedback, screenshots, and wireframe suggestions in this issue.

cc: @Nazarah @bajiat

**Comment by brylie** [comment]
Lets consider advice from the article [Better Form Design: One Thing Per Page](https://www.smashingmagazine.com/2017/05/better-form-design-one-thing-per-page/) during our UX review.

**Comment by xylix** [comment]
Most major UI changes for 1.0 have now been implemented and feedback has been given for them via github issues. The only major UI change left will be the "paths" section, and that will be reviewed in it's own issue.
