### ISSUE TITLE
Implement PUT, POST, DELETE operations for path

### ISSUE THREAD

**Issue by bajiat** [apinf/open-api-designer#8]
A single API path can have several operations: GET, PUT, POST, ALLOW. Allow user to add more than one operation for a path and to select the type of each operation. Each operation will then have subfields defined in Operation Object, which were already implemented for GET (as agreed, first only the fields with type *string*)

# References
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#pathItemObject
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operationObject

Example picture from Swagger UI for Petstore API:
<img width="704" alt="petstore swagger" src="https://cloud.githubusercontent.com/assets/11626388/20174511/c2ae0cca-a746-11e6-97c3-8f2c7022a225.png">

**Comment by tulir** [comment]
I updated the schema so the user can add operation objects and choose the method using a dropdown menu (Commit e2a1393). We still need to figure out why Alpaca isn't outputting the methods as a map. @Xylix is checking if it's a problem in Alpaca and will file an issue there if it is.

**Comment by Xylix** [comment]
We figured that the problem is probably because of Alpaca, so we filed an issue. (gitana/alpaca#444)

**Comment by brylie** [comment]
What about using an array field for operations? Then, the `operation` array item would be an object with a `type` field`. The `type` field would have an `enum` for types (GET, POST, etc).

**Comment by tulir** [comment]
That's kind of how it currently is. Alpaca maps are actually arrays with a `_key` field in the schema and `type: "map"` in the `options` object.
It shouldn't be too hard to make the output JSON go through a function that takes the array and turns it into a map.

**Comment by brylie** [comment]
OK, see the following for an examle of a multi-property array:
http://alpacajs.org/docs/fields/array.html#toc_4

**Comment by brylie** [comment]
The example(s) you gave are using `type: map` for the field. Try using field `type: array`, and refer to the example above.

**Comment by brylie** [comment]
A [similar example on the `array` field documentation](
http://alpacajs.org/docs/fields/array.html#toc_6) shows how a property can be set with `enum` values:

**Comment by tulir** [comment]
If I understood correctly, that's how it's currently done. The `type: "map"` in the options is just supposed to process the output to convert arrays to maps. The type in the options shouldn't affect anything else and the type in the schema is `array`.

**Comment by brylie** [comment]
OK, I am testing locally.

**Comment by tulir** [comment]
The operations have been implemented, so I opened a separate issue (#13) for the output fixing
