### ISSUE TITLE
Use NPM v5+ for project package management

### ISSUE THREAD

**Issue by brylie** [apinf/open-api-designer#88]
What are your thoughts on using Yarn for package management in this project?

# Goal
Decide whether to use Yarn to manage this project's dependencies. Start using Yarn, if it is deemed desirable.

**Comment by MikeRalphson** [comment]
It may be worth waiting until [npm5](https://www.npmjs.com/package/npm5) is released, which should match `yarn` for performance, without having some of the cross-platform issues.

**Comment by mauriciovieira** [comment]
Agreed with @MikeRalphson the task should be `use node 8 and npm 5` 😄

**Comment by MikeRalphson** [comment]
Just a note that npm5 is in fact compatible with all versions of Node from 4.x - I am using it with Node 6.10 without issues so far. Only setting up continuous integration jobs might require extra work.

**Comment by brylie** [comment]
Alright, I will change the title of this task to 'use NPM v5+ for project package management'.

**Comment by mauriciovieira** [comment]
Good idea, @MikeRalphson . I created #118 to keep that in mind.
