### ISSUE TITLE
Implement fixed fields for Parameter Object

### ISSUE THREAD

**Issue by bajiat** [apinf/open-api-designer#9]
Parameter Object is a field for Operation Object. It describes the parameters an API call to a particular endpoint can/must get. For example, if you need to DELETE an item from an endpoint, you would need to know the id of the item and the id would be a parameter (typically a path parameter).

# Reference:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject

See table Fixed fields in section Parameter Object for fields to implement.

# Parameter example for endpoint and operation from Swagger UI / Petstore

<img width="664" alt="swagger ui parameter examples" src="https://cloud.githubusercontent.com/assets/11626388/20214111/bd7e26e4-a814-11e6-90d3-50e19170efa7.png">

**Comment by tulir** [comment]
Fixed fields implemented in commit 4479af5
