### ISSUE TITLE
Create project charter

### ISSUE THREAD

**Issue by brylie** [apinf/open-api-designer#91]
It is important that people know what goals they are working towards. This includes software developers working on small or large projects. In order to promote a clear sense of purpose, and hopefully avoid wasted effort (e.g. feature creep), lets define a **purpose** and **scope** for the OpenAPI Designer.

# Goals
- Discourage waste by working towards clearly defined goals/purpose (e.g. [value proposition](https://en.wikipedia.org/wiki/Value_proposition). 
- Limit the [scope](https://en.wikipedia.org/wiki/Scope_(project_management)) of our work, (discouraging [scope drift/creep](https://en.wikipedia.org/wiki/Scope_creep)), by defining clear boundaries for this project scope. 
- Acknowledge **uncertainty** by assuming, within reason, that the [*project charter*](https://en.wikipedia.org/wiki/Project_charter) to be a [living document](https://en.wikipedia.org/wiki/Living_document).

**Comment by bajiat** [comment]
Discussion notes from meeting with @xylix, @tulir, @brylie 

# Value proposition for OpenAPI designer
User can create an OpenAPI document without knowing the specification or being familiar with json or yaml languages. User is guided by user interface elements such as hints in form fields and mandatory fields.

# Value proposition for OpenAPI hub
User can store and access the OpenAPI documents.

**Comment by bajiat** [comment]
@ccsr Can you review the project charter proposal above?

**Comment by tulir** [comment]
@MikeRalphson Any comments?

**Comment by MikeRalphson** [comment]
@tulir LGTM.

**Comment by tulir** [comment]
Pull requests created at apinf/open-api-designer#169 and apinf/openapi-hub#3
